### ISSUE TITLE
致谢

### ISSUE THREAD

**Issue by Pratitya** [Gnothi-Seauton/gnothi-seauton.github.io#1]
Github似乎无法私信，只能在这里谢谢您一直以来的帮忙！
原项目STAR人数变多，可能会有人盯上，我会及时删掉issues，不必在破坏者上浪费时间。我人在GFW内，紧急状态时会关闭项目，因此希望您可以及时线下备份。
再表谢忱！

Pratitiya 顿首

**Comment by Gnothi-Seauton** [comment]
明白！
我想也没必要回他，毕竟回了他还来劲了
其实主体都已完工，大家都有fork，这个不必担心
也感谢朋友的付出

**Comment by nyctography** [comment]
您好，最近几个月一直与您和 @HuMiaoyan 合作，感谢您的付出。感觉您也应该是名豆友，最近风声渐紧，不知道日后会不会风流云散，想跟您交个朋友，如蒙您不弃，请通过这个邮箱联系我nyctographia@gmail.com，当然如果您觉得没有必要，还请原谅我的打扰。祝您安好，珍重。
